services:
  phntm_cloud_bridge:
    image: phntm/cloud-bridge:latest
    container_name: phntm-cloud-bridge
    hostname: phntm-cloud-bridge.local
    restart: unless-stopped
    privileged: true
    ports:
      - 1337:1337
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ~/cloud_bridge_config.jsonc:/phntm_cloud_bridge/config.jsonc
      #- ~/cloud_bridge:/phntm_cloud_bridge
    command:
      #/bin/sh -c "while sleep 1000; do :; done"
      /bin/sh /phntm_cloud_bridge/run.bridge.sh
